### PR TITLE
improve chopstring speed

### PR DESCRIPTION
**Pull request by jitwit**
see https://github.com/jsoftware/tables_dsv/pull/1

### CODE REVIEW

**Comment by tikkanz** [comment]
Note that `charsub` is only invoked if the opening and closing string delimiters are different. 147cfbd will avoid an `if.` and `~.`.

**Review by tikkanz — CHANGES_REQUESTED** [review]
From my testing,  `+./ (,sd) =/ dat` can be measurably faster than `dat = {. sd`  when `sd` is empty and `dat` is moderately sized. As `dat` increases in size, the performance benefit disappears.
```j
   tst=: 1e8$ tsts=:'The quick brown fox "jumped" over the lazy dog'
   200 timespacex ' tst = {. scalar '
0.0164242 1.34219e8
   200 timespacex ' +./ (,scalar) =/ tst '
0.0171317 1.3422e8
   200 timespacex ' tst = {. empti '
0.0163349 1.34219e8
   200 timespacex ' +./ (,empti) =/ tst '
0.0166101 1.34221e8
```
I suggest changing `dat e. sd` to `dat = {. sd` as per your suggested change for `fixdsv`.

**Comment by jitwit** [comment]
> Note that `charsub` is only invoked if the opening and closing string delimiters are different. [147cfbd](https://github.com/jsoftware/base9/commit/147cfbde0b2bdf6806a0c7ca3550a5ebe11c9ec1) will avoid an `if.` and `~.`.

Ah yes, now I see. 

After 147cfbd, `dat = {. sd`, which is the way to go, unless I misunderstand your suggestion?

**Comment by tikkanz** [comment]
Yes that's what I'm thinking.

**Review by tikkanz — APPROVED** [review]

**Pull request merged**
